name: Tests 
on: push

jobs:
  build:
    runs-on:  ubuntu-22.04
    permissions:
      contents: read
      security-events:  write
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: maven
      - name: Unit and Integration Tests
        run:  |
          chmod +x mvnw
          ./mvnw clean package 

