name: Tests 
on: push

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ekutu/catalog-service
  VERSION:  latest

jobs:
  build:
    runs-on:  ubuntu-22.04
    permissions:
      contents: read
      security-events:  write
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Unit and Integration Tests
        run:  |
          chmod +x mvnw
          ./mvnw clean package 
          
      - name: Validate Kubernetes manifests
        uses: stefanprodan/kube-tools@v1
        with:
          kubectl: 1.24.3
          kubeval: 0.16.1
          command: |
            kubeval --strict -d k8s


  package:
    name: Package and Publish
    if: ${{ github.ref == 'refs/heads/master' }}
    needs:  [ build ]
    runs-on:  ubuntu-22.04
    permissions:
      packages: write
      contents: read
      security-events:  write
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache:  maven

      - name:  Build Container Image
        run:  |
          chmod +x mvnw
          ./mvnw spring-boot:build-image -Dspring-boot.build-image.imageName=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}

      - name: Log Into Container Registry
        run:  echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Publish Container Image
        run: |
          IMAGE_ID=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          echo IMAGE_ID=$IMAGE_ID
          docker image push $IMAGE_ID  
