name: commit-stage
on: push

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ekutu/catalog
  VERSION: latest

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      security-events: write
    steps:
      - name: checkout-source-code
        uses: actions/checkout@v3
      - name: setup-jdk
        uses: actions/setup-java@v3
        with: 
          distribution: temurin
          java-version: 17
          cache:  maven
      - name: build-unit-tests-and-integration-tests
        run:  |
          chmod +x mvnw
          ./mvnw package

  package:
    name: Package and Publish
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: [ build ]
    runs-on:  ubuntu-22.04
    permissions:
      contents: read
      packages: write
      security-events:  write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
        java-version: 17
        cache:  maven
      - name: Build Container Image
        run:  |
          chmod +x mvnw
          ./mvnw spring-boot:build-image --imageName ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
      - name: Log into container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Container Image
        run:  docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
